### ISSUE TITLE
Step 13 issue

### ISSUE THREAD

**Issue by abhisarda10** [arthas009/Traffic-Sign-Detection-using-Faster-R-CNN#3]
![15860871618645621473603252935214](https://user-images.githubusercontent.com/63191393/78473835-41eff780-7761-11ea-897d-a3da23b24561.jpg)
Hello I am trying to do this code 
But having error same in step number 13 please help me

**Comment by abhisarda10** [comment]
Please help me sir I am in trouble now where I don't know what to do

**Comment by Shawkat-196** [comment]
> Please help me sir I am in trouble now where I don't know what to do
Hope it will help
While generating the train and test.record files you need to replace the "\" with "/" in your commands, and for attribute error visit the below link: https://github.com/tensorflow/tensorflow/issues/34431

**Comment by abhisarda10** [comment]
It's not working
Exactly what I have to do

**Comment by abhisarda10** [comment]
Can anyone help me getting on TeamViewer please

**Comment by danielivan09** [comment]
Traceback (most recent call last):
File "generate_tfrecord.py", line 108, in
tf.compat.v1.app.run()
File "C:\Users\ivand\anaconda3\envs\tensorflow2\lib\site-packages\tensorflow\python\platform\app.py", line 40, in run
_run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
File "C:\Users\ivand\anaconda3\envs\tensorflow2\lib\site-packages\absl\app.py", line 303, in run
_run_main(main, args)
File "C:\Users\ivand\anaconda3\envs\tensorflow2\lib\site-packages\absl\app.py", line 251, in _run_main
sys.exit(main(argv))
File "generate_tfrecord.py", line 94, in main
writer = tf.io.TFRecordWriter(FLAGS.output_path)
File "C:\Users\ivand\anaconda3\envs\tensorflow2\lib\site-packages\tensorflow\python\lib\io\tf_record.py", line 218, in init
compat.as_bytes(path), options._as_record_writer_options(), status)
File "C:\Users\ivand\anaconda3\envs\tensorflow2\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 548, in exit
c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: Failed to create a NewWriteableFile: : The system cannot find the path specified.
; No such process

i have an error like this, please help me sir
